---
- name: gridftp
  src: https://github.com/EMBL-EBI-TSI/ansible-gridftp.git
  scm: git
  version: 1.4.2

- name: simpleca
  src: https://github.com/EMBL-EBI-TSI/ansible-simpleca.git
  scm: git
  version: 1.0.0
