---
gridftp_ca_local_certs:
  - name: TERENA-SSL-CA-3
    subject: '/C=NL/ST=Noord-Holland/L=Amsterdam/O=TERENA/CN=TERENA SSL CA 3'
    policy: '/C=CZ/*/CN=globus.du3.cesnet.cz'
    cert_file: files/TERENA-SSL-CA-3.pem

  - name: DigiCertAssuredIDRootCA-Root
    subject: '/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Assured ID Root CA'
    policy: '"/C=US/O=DigiCert Grid/OU=www.digicert.com/CN=DigiCert Grid Trust CA" "/C=US/O=DigiCert Grid/OU=www.digicert.com/CN=DigiCert Grid Trust CA G2" "/C=NL/ST=Noord-Holland/L=Amsterdam/O=TERENA/CN=TERENA eScience Personal CA 3" "/C=NL/ST=Noord-Holland/L=Amsterdam/O=TERENA/CN=TERENA eScience SSL CA 3" /C=NL/ST=Noord-Holland/L=Amsterdam/O=TERENA/CN=TERENA SSL CA 3"'
